/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Price = {
  _type: "price";
  amount?: number;
  currency?: string;
  label?: string;
  priceFrom?: boolean;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type SeoPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "seoPage";
};

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | ServiceReference
    | ProjectReference
    | TestimonialReference
    | SeoPageReference
    | SiteSettingsReference;
  language?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  navLabels?: Array<string>;
  footerText?: string;
  heroHeadline?: string;
  heroSubline?: string;
  contactEmail?: string;
  address?: string;
  steuernummer?: string;
  vatNote?: string;
  aboutPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultSeo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
  language?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SeoPage = {
  _id: string;
  _type: "seoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  metaDescription?: string;
  language?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  author?: string;
  company?: string;
  outcomeValue?: string;
  outcomeLabel?: string;
  order?: number;
  language?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  outcomeNote?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
  language?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  blurb?: string;
  price?: Price;
  priceOnRequest?: boolean;
  includes?: Array<string>;
  order?: number;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Price
  | TranslationMetadata
  | InternationalizedArrayReference
  | ServiceReference
  | ProjectReference
  | TestimonialReference
  | SeoPageReference
  | SiteSettingsReference
  | InternationalizedArrayReferenceValue
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SeoPage
  | Slug
  | Testimonial
  | Project
  | Service
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service" && language == $locale] | order(order asc){     _id, title, slug, blurb,     price{ amount, currency, label, priceFrom },     priceOnRequest, includes   }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  blurb: string | null;
  price: {
    amount: number | null;
    currency: string | null;
    label: string | null;
    priceFrom: boolean | null;
  } | null;
  priceOnRequest: boolean | null;
  includes: Array<string> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && language == $locale] | order(order asc){     _id, title, slug, summary, outcomeNote, image, order   }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  outcomeNote: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && language == $locale && slug.current == $slug][0]{     _id, title, slug, summary, outcomeNote, image, order   }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  outcomeNote: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  order: number | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && language == $locale] | order(order asc){     _id, quote, author, company, outcomeValue, outcomeLabel   }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  author: string | null;
  company: string | null;
  outcomeValue: string | null;
  outcomeLabel: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SEO_PAGES_QUERY
// Query: *[_type == "seoPage" && language == $locale]{     _id, title, slug, heading, body, metaDescription   }
export type SEO_PAGES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  heading: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  metaDescription: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SEO_PAGE_BY_SLUG_QUERY
// Query: *[_type == "seoPage" && language == $locale && slug.current == $slug][0]{     _id, title, slug, heading, body, metaDescription   }
export type SEO_PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  heading: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  metaDescription: string | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && language == $locale][0]{     _id, siteTitle, navLabels, footerText, heroHeadline, heroSubline,     contactEmail, address, steuernummer, vatNote, defaultSeo,     aboutPhoto   }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  siteTitle: string | null;
  navLabels: Array<string> | null;
  footerText: string | null;
  heroHeadline: string | null;
  heroSubline: string | null;
  contactEmail: string | null;
  address: string | null;
  steuernummer: string | null;
  vatNote: string | null;
  defaultSeo: {
    metaTitle?: string;
    metaDescription?: string;
  } | null;
  aboutPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "service" && language == $locale] | order(order asc){\n     _id, title, slug, blurb,\n     price{ amount, currency, label, priceFrom },\n     priceOnRequest, includes\n   }': SERVICES_QUERY_RESULT;
    '*[_type == "project" && language == $locale] | order(order asc){\n     _id, title, slug, summary, outcomeNote, image, order\n   }': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && language == $locale && slug.current == $slug][0]{\n     _id, title, slug, summary, outcomeNote, image, order\n   }': PROJECT_BY_SLUG_QUERY_RESULT;
    '*[_type == "testimonial" && language == $locale] | order(order asc){\n     _id, quote, author, company, outcomeValue, outcomeLabel\n   }': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "seoPage" && language == $locale]{\n     _id, title, slug, heading, body, metaDescription\n   }': SEO_PAGES_QUERY_RESULT;
    '*[_type == "seoPage" && language == $locale && slug.current == $slug][0]{\n     _id, title, slug, heading, body, metaDescription\n   }': SEO_PAGE_BY_SLUG_QUERY_RESULT;
    '*[_type == "siteSettings" && language == $locale][0]{\n     _id, siteTitle, navLabels, footerText, heroHeadline, heroSubline,\n     contactEmail, address, steuernummer, vatNote, defaultSeo,\n     aboutPhoto\n   }': SITE_SETTINGS_QUERY_RESULT;
  }
}
